username: gannon
spring:
  database:
    uri: jdbc:oracle:thin:@139.155.245.150:11521:orcl
    username: scott
    password: scott
  cloud:
    nacos:
      server-addr: 192.168.2.11:8888
      username: nacos
      password: nacos
